/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as LeasesIndexRouteImport } from './routes/leases.index'
import { Route as DisputesIndexRouteImport } from './routes/disputes.index'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as LeasesLeaseIdRouteImport } from './routes/leases.$leaseId'
import { Route as DisputesNewRouteImport } from './routes/disputes.new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesIndexRoute = LeasesIndexRouteImport.update({
  id: '/leases/',
  path: '/leases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIndexRoute = DisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesLeaseIdRoute = LeasesLeaseIdRouteImport.update({
  id: '/leases/$leaseId',
  path: '/leases/$leaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesNewRoute = DisputesNewRouteImport.update({
  id: '/disputes/new',
  path: '/disputes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/disputes/new': typeof DisputesNewRoute
  '/leases/$leaseId': typeof LeasesLeaseIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/disputes/': typeof DisputesIndexRoute
  '/leases/': typeof LeasesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/disputes/new': typeof DisputesNewRoute
  '/leases/$leaseId': typeof LeasesLeaseIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/disputes': typeof DisputesIndexRoute
  '/leases': typeof LeasesIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/disputes/new': typeof DisputesNewRoute
  '/leases/$leaseId': typeof LeasesLeaseIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/disputes/': typeof DisputesIndexRoute
  '/leases/': typeof LeasesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/disputes/new'
    | '/leases/$leaseId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/disputes/'
    | '/leases/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/disputes/new'
    | '/leases/$leaseId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/disputes'
    | '/leases'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/disputes/new'
    | '/leases/$leaseId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/disputes/'
    | '/leases/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DisputesNewRoute: typeof DisputesNewRoute
  LeasesLeaseIdRoute: typeof LeasesLeaseIdRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  DisputesIndexRoute: typeof DisputesIndexRoute
  LeasesIndexRoute: typeof LeasesIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/': {
      id: '/leases/'
      path: '/leases'
      fullPath: '/leases/'
      preLoaderRoute: typeof LeasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/': {
      id: '/disputes/'
      path: '/disputes'
      fullPath: '/disputes/'
      preLoaderRoute: typeof DisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/$leaseId': {
      id: '/leases/$leaseId'
      path: '/leases/$leaseId'
      fullPath: '/leases/$leaseId'
      preLoaderRoute: typeof LeasesLeaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/new': {
      id: '/disputes/new'
      path: '/disputes/new'
      fullPath: '/disputes/new'
      preLoaderRoute: typeof DisputesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DisputesNewRoute: DisputesNewRoute,
  LeasesLeaseIdRoute: LeasesLeaseIdRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  DisputesIndexRoute: DisputesIndexRoute,
  LeasesIndexRoute: LeasesIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
